# Generated by Django 2.2 on 2019-12-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=100)),
                ('IpAddress', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('post', models.CharField(max_length=5)),
                ('location', models.CharField(max_length=50)),
                ('hostname', models.CharField(max_length=50)),
                ('upload', models.CharField(max_length=100)),
                ('download', models.CharField(max_length=100)),
                ('ping', models.CharField(max_length=100)),
                ('organisation', models.CharField(max_length=100)),
            ],
        ),
    ]
